### ISSUE TITLE
Can't update the game. 

### ISSUE THREAD

**Issue by gagantous** [an-anime-team/the-honkers-railway-launcher#109]
![IMG_20240313_173556](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/24579576/87596b67-d6a3-4686-9f4f-2cfdd55cc15c)

Why the update button got blocked ?

**Comment by krypt0nn** [comment]
It will show the reason if you hover it. Your installed version is too outdated. You have to uninstall the game and install it again.

**Comment by gagantous** [comment]
All right, thanks man

**Comment by Interpause** [comment]
would it be nice if the update button instead warned the user the install is too old upon clicking, then confirm to reinstall?

**Comment by CritLoren** [comment]
How do you do that? I tried clicking Repair game and it doesn't give me the option.
