### ISSUE TITLE
1.5.3 update requires the org.gnome.Platform/x86_64/45 which was not found 

### ISSUE THREAD

**Issue by Korysovec** [an-anime-team/the-honkers-railway-launcher#113]
Hello,

When I am updating the launcher (flatpak) from 1.5.2 to 1.5.3 I get this error message. Overall 1.5.2 works fine though.

`Application moe.launcher.the-honkers-railway-launcher/x86_64/master requires the org.gnome.Platform/x86_64/45 which was not found`

Distribution: Arch Linux x86_64 
Kernel: 6.7.8-arch1-1
DE: Plasma 6.0.1

**Comment by krypt0nn** [comment]
Just... install it?

```
flatpak install org.gnome.Platform/x86_64/45
```

**Comment by Korysovec** [comment]
The thing is I already have it installed. I can try reinstalling the launcher I guess.
