### ISSUE TITLE
So I just finished the 2.1 Story, then my game turns black

### ISSUE THREAD

**Issue by DinhHoangDuy** [an-anime-team/the-honkers-railway-launcher#117]
After the "To be continued" letter, the game blacks out and nothing happens. I just can't go to the open world or continue the story. The game just stuck there, every time. I can't do anything but stare at the black screen and I close the game manually
Right now, I don't have my secondary PC, so I need help here.

This is the console when I run the game using the terminal:
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/81969152/8600df54-cc7e-46a0-b48d-5c3b281739fe)
These warnings appeared 2 times: when the game starts and when the cutscene starts.

Specs:
- i7 1065G7
- 16GB RAM (2x8)
- OS: POP!_OS 22.04 LTS

**Comment by CesOk** [comment]
Same problem here

**Comment by mkrsym1** [comment]
Wine-GE-Proton cannot play the new cutscenes, Wine 9.5 with GStreamer libraries is required. In the flatpak version, to fix this, do the following:
1. Update to the latest launcher version with `flatpak update`
2. Clear the GStreamer plugin cache with `rm -rf "$HOME/.var/app/moe.launcher.the-honkers-railway-launcher/cache/gstreamer-1.0"`
3. Switch to Wine-Staging-TkG 9.5 or later in the launcher settings (under components)
4. Open launcher folder, close the launcher, and delete the entire `prefix` folder
5. Reopen the launcher, click "Create prefix"
6. Go to launcher settings, switch to a different DXVK version, then back

For native packages, make sure that `gst-pulgins-base`, `gst-plugins-good`, `gst-plugins-bad`, `gst-libav` are all installed, then continue from step 3 of the above instructions.

You would not have needed to do this if you had only recently installed the launcher, as the necessary codec is now included in the flatpak package, the necessary GStreamer libraries are now included in most native package dependencies, and Wine-Staging-TkG is now the default runner for all launcher packages.

**Comment by DinhHoangDuy** [comment]
Yeah I heard about that change on Discord, but I forgot to close this issue. After all I continued it on my phone so yeah, so I might consider trying it in the future, since Wine-Ge-Proton still give me slightly better performance to me

**Comment by DinhHoangDuy** [comment]
> Wine-GE-Proton cannot play the new cutscenes, Wine 9.5 with GStreamer libraries is required. In the flatpak version, to fix this, do the following:
> 1. Update to the latest launcher version with `flatpak update`
> 2. Clear the GStreamer plugin cache with `rm -rf "$HOME/.var/app/moe.launcher.the-honkers-railway-launcher/cache/gstreamer-1.0"`
> 3. Switch to Wine-Staging-TkG 9.5 or later in the launcher settings (under components)
> 4. Open launcher folder, close the launcher, and delete the entire `prefix` folder
> 5. Reopen the launcher, click "Create prefix"
> 6. Go to launcher settings, switch to a different DXVK version, then back
> 
> For native packages, make sure that `gst-pulgins-base`, `gst-plugins-good`, `gst-plugins-bad`, `gst-libav` are all installed, then continue from step 3 of the above instructions.
> 
> You would not have needed to do this if you had only recently installed the launcher, as the necessary codec is now included in the flatpak package, the necessary GStreamer libraries are now included in most native package dependencies, and Wine-Staging-TkG is now the default runner for all launcher packages. 
> 
> 

Yeah I heard about that change on Discord, but I forgot to close this issue. After all I continued it on my phone so yeah, so I might consider trying it in the future, since Wine-Ge-Proton still give me slightly better performance to me
