### ISSUE TITLE
Game stopping suddenly

### ISSUE THREAD

**Issue by dan-dan-dslkfnsdoifjsdoim** [an-anime-team/the-honkers-railway-launcher#127]
while playing the game suddenly stops

**Comment by AndreasYNY** [comment]
have you tried running the game again?

**Comment by dan-dan-dslkfnsdoifjsdoim** [comment]
i did it just stops again in the middle of fights

**Comment by dan-dan-dslkfnsdoifjsdoim** [comment]
Sorry this is not really a problem. The reason why my game stops is because the processor being used is intel. It means every time i play, intel can't handle it so it just closes the game.
