### ISSUE TITLE
lacking flatpak dependency

### ISSUE THREAD

**Issue by chenxiex** [an-anime-team/the-honkers-railway-launcher#13]
When installing using flatpak, it returns `error: The application moe.launcher.the-honkers-railway-launcher/x86_64/master requires the runtime org.gnome.Platform/x86_64/43 which was not found`. Both flathub and launcher.moe source had already been added.

**Comment by Mar0xy** [comment]
This happens to some people that the easy fix is installing that before the launcher by running
`flatpak install org.gnome.Platform//43`

**Comment by arlarzelere3** [comment]
I was able to get this to work by updating in the terminal rather than the discover store.  On a steam deck if that matters
