### ISSUE TITLE
Starts a new game on an existing account - OLED

### ISSUE THREAD

**Issue by TheNightwasp** [an-anime-team/the-honkers-railway-launcher#132]
The launcher installed and loads beautifully.  I was able to log into my account just fine, but instead of resuming my existing game it starts the game from the beginning with a new UID.  Checking my account on PC and mobile after repeated attempts to use Honkers, they resume the existing game correctly

**Comment by mkrsym1** [comment]
Verify that you selected the same server (e.g. that if you were playing on Europe, verify that Europe is selected). Game progress is not shared between servers.

**Comment by TheNightwasp** [comment]
You're 100% right, and this didn't occur to me... but I don't remember selecting a server at any point either...
I'll check again when I can in a few hours.  Thank you for the very probable solution!
