### ISSUE TITLE
Unity Crash aftr use "Ult". (Need kernel downgrade) Closed

### ISSUE THREAD

**Issue by ax6842** [an-anime-team/the-honkers-railway-launcher#141]
Good day to all .
OS: Fedora Linux 40 (Workstation Edition)
Kernel: 6.8.9-300.fc40.x86_64 

Anime Launcher SDK: 1.12.10
Anime Game Core: 1.17.8

gtk: 4.12.5
libadwaita: 1.4.4
pango: 1.51.2
cairo: 1.18.0

debug.log:
 https://drive.google.com/file/d/1JZvb3sIIt2weaBYTo9_ho8TMpkJXYCTT/view?usp=sharing

2 day in row on Fedora 40 after update kernel on any battle if I use Ultimate I  take Crash Unity on Ultimate animation and finish if I continu -  Kernel Crush. Before play normal, play parallel Genshin on PortProton and no have problem. This problem start 12.05.2024
Only play in HSR,  if i try again and again  crash xorg-x11-server-Xwayland. 
W - Kernel issued warning and Kernel Crush.
I try different WINE version GE-Proton, Lutris, Soda - crush. I chek game file .

If I start play Genshin Impact  and HSR  parallel  -Genshin is close and lunch to luncher update (but I have last version luncher), or HSR crash immediately. 

Play in Genshin use PortProton or any steam proton support game (example 7dtd) I'm no have any problems. 

Thanks.

**Comment by sleepy-day** [comment]
Do you have an AMD graphics card? There's a fix in the latest kernel (6.9) if so, otherwise you might need to downgrade to an older one https://gitlab.freedesktop.org/drm/amd/-/issues/3343

**Comment by ax6842** [comment]
> Do you have an AMD graphics card? There's a fix in the latest kernel (6.9) if so, otherwise you might need to downgrade to an older one https://gitlab.freedesktop.org/drm/amd/-/issues/3343

Yes - I use  AMD GPU.
My PC:
MB: GA-AB350M-DS3H V2
CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz
GPU: AMD ATI Radeon RX 570

1 hours ago I take update, but no kernel. Wait update kernel.
