### ISSUE TITLE
Autoplay seems to not work in background

### ISSUE THREAD

**Issue by Balssh** [an-anime-team/the-honkers-railway-launcher#148]
I have installed the game on Arch Linux and I'm using Hyperland. The game works fine, but I noticed that autoplay is not seeming to work (or works very delayed) when the game is not focused. Is this behavior known/has any fixes? Thanks for your efforts!

**Comment by WiseEXE** [comment]
Specs:
Arch
NVIDIA 2080
Ryzen 1700X
32GB RAM

I've noticed this to be an issue with the game overall and not exclusively connected to autoplay. It seems that whenever the game isn't focused either a hard FPS limit is placed, or the process gets limited resources whenever the game isn't focused. You can verify this yourself using DXVK overlay and taking note of  the huge amount of idling that displays in the graph.

**Comment by Balssh** [comment]
I'm also on nvidia. Didn't try with an overlay but indeed the symptoms match your description @WiseEXE

**Comment by Balssh** [comment]
For everyone that encountered this issue: disabling vsync solves it and it works as expected in the backround.
