### ISSUE TITLE
Launcher is stuck on loading data

### ISSUE THREAD

**Issue by ZenHWu** [an-anime-team/the-honkers-railway-launcher#151]
Using arch and flatpak, I just updated to the newest launcher using `flatpak update`

The launcher is stuck on the screen, "loading data" on launch, for an indefinite amount of time.

I've attempted to restart my computer, as well as to reinstall the launcher.

![Screenshot_20240618_220354](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/104530554/0d8bac4f-2b14-45a0-ae8b-59db0bbf8151)

Debug file here:
[debug.log](https://github.com/user-attachments/files/15902894/debug.log)

**Comment by krypt0nn** [comment]
Is it still stuck?

**Comment by ZenHWu** [comment]
Issue was resolved when I deleted all user data and reinstalled the launcher.

Will mark as resolved, though it may warrant a bugfix.

Thanks!

**Comment by lovelylucina** [comment]
Sorry if this is a silly question but how did you delete user data? Im having the same problem and deleting and reinstalling the launcher alone isnt fixing it

**Comment by ZenHWu** [comment]
> Sorry if this is a silly question but how did you delete user data? Im having the same problem and deleting and reinstalling the launcher alone isnt fixing it

Try the following command:

`flatpak uninstall --delete-data moe.launcher.the-honkers-railway-launcher`

**Comment by lovelylucina** [comment]
> > Sorry if this is a silly question but how did you delete user data? Im having the same problem and deleting and reinstalling the launcher alone isnt fixing it
> 
> Try the following command:
> 
> `flatpak uninstall --delete-data moe.launcher.the-honkers-railway-launcher`

That was the one that did it, seriously thank you so much! I’m really new to this kind of stuff so I really appreciate it a ton!
