### ISSUE TITLE
Unable to play the game already updated the launcher and all.

### ISSUE THREAD

**Issue by EnglishPatchFanatic** [an-anime-team/the-honkers-railway-launcher#152]
Updated the launcher and unable to start the game pressing the update button does not do anything.

I tried repairing the game by verifying all files but to no avail it does not work

See attached image
![IMG20240620105811](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/75802913/cd14e939-338e-4081-8e60-0ccfa48647c7)
![IMG20240620105803](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/75802913/8e248a09-d378-417b-9caf-48eeba6aa0ca)

Please fix thanks

**Comment by xstraok** [comment]
Your game version might be too old. 
Click the settings icon and scroll down a bit. If the game version is older than 2.2.0, then you must delete the game files and fully reinstall unfortunately.

**Comment by AtomicWn** [comment]
I have the exact same problem, some person on the discord too.
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/99515101/fe7967d5-c844-43a3-96e7-14aaec6e0c46)

**Comment by anasazmi571** [comment]
I can confirm having the same issue. My Update Manager didn't see the update for the launcher, so I manually triggered update through `flatpak update`. It was only afterwards that I saw the button change to Update, which I clicked. The app downloads the update patch afterwards, then after finishing, it turns to the same look on OP. The Update button is disabled.
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/34757452/2c950b66-d153-4e5d-9aab-835d8fcb42e4)
Below is the patch version.
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/34757452/4edeb3a9-4e2f-4721-a4f3-496ada3c3f12)

**Comment by Drakhon33** [comment]
I had the same problem. After looking through the log file I noticed that my Japanese voice pack was outdated. Don't know why that one did not update or how to update it, but since I basically only use the English voices I removed the Japanese voices, which allowed me to start the game again. Hope that helps.

**Comment by EnglishPatchFanatic** [comment]
Mines also at 2.3.0.

Is the option to only delete all game files and reinstall HSR?

**Comment by Serpentian** [comment]
Deleted `HSR` directory, reinstalled the game, nothing changes. Still version mismatch

**Comment by forgotten-memory** [comment]
I had this same issue, my voiceovers were not updated along with the rest of the game when I clicked Update on the launcher. I figured this out after looking at the debug.log. After the update, the Update button was yellow just like above. I fixed this by deleting all the game voiceovers in the launcher settings and then reinstalling just the voiceover for the language I wanted.

**Comment by EnglishPatchFanatic** [comment]
So all in all we agree and can close this issue for now as the workaround is to delete all game data and redownload the game after the recent update!

I will be closing this haha 👯

**Comment by Piece-kun** [comment]
Ok so while this thread is older, this is the one that comes up when googling the issue.

The solution for this was found that does not require redownloading 50+ gigs, every time you want to play.

Step 1: Open game folder.

<img width="588" height="288" alt="Image" src="https://github.com/user-attachments/assets/c09c227c-f797-4c9a-b50d-1801f700f373" />

Step 2: Locate `.version` file and copy it. Make sure to enable _show hidden files_ to see it.

Step 3: Assuming you did not rename game folder from `HSR` and you play with english voice you will need to paste the `.version` file in this directory, starting from game folder.
`/HSR/StarRail_Data/Persistent/Audio/AudioPackage/Windows/English/`
