### ISSUE TITLE
Game doesn’t remember login info

### ISSUE THREAD

**Issue by Eirakkun** [an-anime-team/the-honkers-railway-launcher#17]
Not sure if this is a bug or if it's how the patching process works (or if the game is just this way), but the game doesn't remember my login info (which means I have to re-login every time I start through the launcher).

This is unlike in GI where it remembers (on PC or Proton), not sure if HSR remembers login info on vanilla PC version either because I'm only really playing through the launcher.

**Comment by Mar0xy** [comment]
This is an issue with only the flatpak build for some reason and no one can figure out why this is happening.

**Comment by Eirakkun** [comment]
> This is an issue with only the flatpak build for some reason and no one can figure out why this is happening.

Oh. Maybe file permissions? I can try to fiddle around with flatseal to see if that fixes things.

**Comment by Eirakkun** [comment]
Can confirm that updating to any of the Proton 8 versions (in my case Wine-GE-Proton-8.5) works in making the flatpak version of HRL remember login info.

But you seem to lose FSR in the process. As the changelogs of Proton GE has noted, they need to rebase FSR for the new Proton, so no FSR apparently.
