### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by GyuminLeo** [an-anime-team/the-honkers-railway-launcher#171]
as the title says the game is not launching when it worked before reboot
using Ubuntu 24.04

[Screencast from 2024-08-08 10-29-58.webm](https://github.com/user-attachments/assets/68056989-9ff0-4258-bd08-15abde15d3ce)

Genshin works fine

**Comment by GyuminLeo** [comment]
`[!] [stderr] 0148:err:fsync:fsync_init Failed to open fsync shared memory file; make sure no stale wineserver instances are running without WINEFSYNC.
[!] [stderr] `

the game.log file

**Comment by xdenotte** [comment]
what settings do you have enabled, dxvk and wine version?
Is gamescope enabled?

**Comment by GyuminLeo** [comment]
reinstalled the app and star rail fixed the issue
