### ISSUE TITLE
stuck at decompressing after download

### ISSUE THREAD

**Issue by koruninn** [an-anime-team/the-honkers-railway-launcher#181]
2024-09-11T16:26:55.687297Z  INFO honkers_railway_launcher::ui::components::progress_bar: Downloading finished
    at src/ui/components/progress_bar.rs:165
    in relm4::component::r#async::builder::update_with_view with input: UpdateFromState(InstallerUpdate(DownloadingFinished)), component: "honkers_railway_launcher::ui::components::progress_bar::ProgressBar", id: "0x7ffc9066dd50"

  2024-09-11T16:26:55.741820Z TRACE anime_game_core::installer::installer: Extracting archive
    at /run/build/railway/cargo/vendor/anime-game-core/src/installer/installer.rs:239

  2024-09-11T16:26:55.741941Z TRACE anime_game_core::installer::archives: Extracting archive
    at /run/build/railway/cargo/vendor/anime-game-core/src/installer/archives.rs:241
    in anime_game_core::installer::archives::extract with folder: "/home/koru/.var/app/moe.launcher.the-honkers-railway-launcher/data/honkers-railway-launcher/HSR"

  2024-09-11T16:26:55.742002Z  INFO honkers_railway_launcher::ui::components::progress_bar: Updating permissions finished
    at src/ui/components/progress_bar.rs:166
    in relm4::component::r#async::builder::update_with_view with input: UpdateFromState(InstallerUpdate(UpdatingPermissionsFinished)), component: "honkers_railway_launcher::ui::components::progress_bar::ProgressBar", id: "0x7ffc9066dd50"

  2024-09-11T16:26:56.016314Z  INFO honkers_railway_launcher::ui::components::progress_bar: Unpacking finished
    at src/ui/components/progress_bar.rs:167
    in relm4::component::r#async::builder::update_with_view with input: UpdateFromState(InstallerUpdate(UnpackingFinished)), component: "honkers_railway_launcher::ui::components::progress_bar::ProgressBar", id: "0x7ffc9066dd50"

os: nobara 40
kernel:  6.10.7
de: gnome 46 (wayland)
[debug.log](https://github.com/user-attachments/files/16966719/debug.log)

**Comment by Balssh** [comment]
How much have you waited at unpacking?

**Comment by koruninn** [comment]
left it downloading and unpacking overnight, then i tried again several times giving it at least one hour but nothing seems to happen. i deleted the files to see if something was wrong with them and then reinstalled everything but no luck whatsoever

**Comment by Balssh** [comment]
I suspect it's related to https://github.com/an-anime-team/the-honkers-railway-launcher/issues/180
I also had the issue with being stuck at download/unpack in the previous banner but it solved itself by deleting the launcher folder several times. But now that doesn't seem to work anymore.

**Comment by koruninn** [comment]
yeah, i thought so too. as i'm writing this comment i keep repeating the process but i'm not feeling very optimistic about it. i guess for now i'll just play on my phone and stream the content via scrcpy

**Comment by dasBente** [comment]
I've had this issue on both Nobara and Steamdeck, but on Steamdeck I could fix it by just unpacking the downloaded archive myself. No such luck on Nobara, where once the unpacking starts the archive is nowhere to be found so that doesn't work unfortunately.
Notably, the file is present during download and only seems to disappear afterwards. Also, curiously I didn't run into this issue when I toyed around with Endeavour OS a couple of weeks back (or when I first installed the launcher on Steamdeck some months ago before somehow flubbing the 2.4 update and having to re-download the game files).

**Comment by koruninn** [comment]
i had the same issue where i couldn't find the files at all. i joined the discord server last night and i could download the 7z files and extract them in its respective path and the game seemed to work fine until i got a black screen. i tried using ge proton since that worked the best for me before and also gplaysync. that didn't work either and after trying different settings for dxvk the result was the same

**Comment by Yuusha0** [comment]
I have the same issue on Mageia 9 using the Flatpak version. The compressed file just vanishes after the download, and the installer is stuck at unpacking the file.

**Comment by karuboniru** [comment]
Don't know if its related, I noticed that the downloaded file is only a single file from a multi-part archives, and the attempt of the decompression started before the full archive was downloaded.

**Comment by koruninn** [comment]
what i did to solve this was to download all the 7z files from the discord server, then use peazip to extract them in their respective folder and then open the launcher, it immediately started to work properly and the game worked flawlessly
