### ISSUE TITLE
Can i make a youtube video about the game installation ? 

### ISSUE THREAD

**Issue by gagantous** [an-anime-team/the-honkers-railway-launcher#19]
Is it okay if i made a video about how to install star rail using this project ? Or it will harm the project activity if hoyoverse know about it?

**Comment by krypt0nn** [comment]
We're not against as far as you keep basic anti-seo practices in mind, like not referencing to the game itself and call it "The Honkers Railway", or something like that 🚂

**Comment by mkrsym1** [comment]
Thanks for asking though! Barely anyone does that, and then either notifies us after the fact, or doesn't at all

**Comment by gagantous** [comment]
Thank you very much 🙏, what i would make is just perform testing gameplay on steamdeck using this project, for anyone who will watch it can used the link on the description that will linked to this repository

**Comment by mkrsym1** [comment]
Please try to avoid direct links. You can mention the project name in the video, it's rather easy to find

**Comment by gagantous** [comment]
Okay i will mentioned it on description without using direct link

**Comment by gagantous** [comment]
here is the video link that i have uploaded! https://youtu.be/2MCy6y1WS9w

Thank you very much!

**Comment by krypt0nn** [comment]
You can also use `--run-game` launch flag to open the game instead of the launcher
