### ISSUE TITLE
Can't download the game (minreq error - unexpected end of file)

### ISSUE THREAD

**Issue by DigitalStarSys** [an-anime-team/the-honkers-railway-launcher#192]
Dealing with a fresh install of the game + launcher, and the download fails at 73.18% with a "minreq error - unexpected end of file". Sometimes this error shows up during early install, too, but it can usually be powered through by simply retrying the download.

Tested on Arch Linux (AUR) and NixOS (flatpak), to no avail. It's the same issue on both sides, running version 1.9.0 of the launcher.

Attached debug.log. 

[debug.log](https://github.com/user-attachments/files/17351335/debug.log)

**Comment by DigitalStarSys** [comment]
Update: I tried again a few hours later and it *did* seem to work. Maybe some sort of rate-limit? Unsure if I should leave this issue open or not because this does seem like unintended behavior.

**Comment by participle38** [comment]
Same problem.
[debug.log](https://github.com/user-attachments/files/17449281/debug.log)
