### ISSUE TITLE
Honkers Railway Game freezing at login

### ISSUE THREAD

**Issue by KorinFlakes** [an-anime-team/the-honkers-railway-launcher#2]
So I recently downloaded this from the AUR but whenever I attempt to login after launch the game freezes. Sometimes it will get past the login to the verification email but will freeze on that screen.
Any help would be greatly appreciated.
[debug.log](https://github.com/an-anime-team/the-honkers-railway-launcher/files/11379067/debug.log)

`inxi -Fxz `

> System:
>   Kernel: 6.2.13-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 12.2.1
>     Desktop: GNOME v: 43.5 Distro: EndeavourOS base: Arch Linux

> Machine:
>   Type: Desktop Mobo: Gigabyte model: B550M DS3H serial: <superuser required>
>     UEFI: American Megatrends LLC. v: F17b date: 02/08/2023

> CPU:
>   Info: 6-core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 2
>     rev: 0 cache: L1: 384 KiB L2: 3 MiB L3: 32 MiB
>   Speed (MHz): avg: 3966 high: 3973 min/max: 2200/4208 boost: enabled cores:
>     1: 3958 2: 3964 3: 3969 4: 3965 5: 3963 6: 3968 7: 3964 8: 3971 9: 3968
>     10: 3968 11: 3973 12: 3965 bogomips: 86268
>   Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm

> Graphics:
>   Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
>     vendor: Sapphire driver: amdgpu v: kernel arch: RDNA-2 bus-ID: 08:00.0
>   Display: wayland server: X.Org v: 23.1.1 with: Xwayland v: 23.1.1
>     compositor: gnome-shell driver: X: loaded: amdgpu
>     unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu resolution:
>     1: 1920x1080~60Hz 2: 1920x1080~60Hz
>   API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon RX 6700 XT (navi22
>     LLVM 15.0.7 DRM 3.49 6.2.13-arch1-1) direct-render: Yes

> Audio:
>   Device-1: AMD Navi 21/23 HDMI/DP Audio driver: snd_hda_intel v: kernel
>     bus-ID: 1-2:3
>   Device-2: AMD Starship/Matisse HD Audio vendor: Gigabyte
>     driver: snd_hda_intel v: kernel bus-ID: 0a:00.4
>   Device-3: Elgato Systems GmbH Wave:1 type: USB driver: snd-usb-audio
>   Device-4: Dell C2422HE type: USB driver: hid-generic,snd-usb-audio,usbhid
>     bus-ID: 3-2.3:6
>   API: ALSA v: k6.2.13-arch1-1 status: kernel-api
>   Server-1: PipeWire v: 0.3.70 status: active

> Network:
>   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
>     vendor: Gigabyte driver: r8169 v: kernel port: f000 bus-ID: 05:00.0
>   IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
>   Device-2: Realtek RTL8153 Gigabit Ethernet Adapter type: USB driver: r8152
>     bus-ID: 4-2.2:5
>   IF: enp10s0f3u2u2 state: down mac: <filter>

> Bluetooth:
>   Device-1: Realtek Bluetooth Radio type: USB driver: btusb v: 0.8
>     bus-ID: 1-5:7
>   Report: rfkill ID: hci0 rfk-id: 1 state: up address: see --recommends

> Drives:
>   Local Storage: total: 10.46 TiB used: 2.68 TiB (25.6%)
>   ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 500GB
>     size: 465.76 GiB temp: 45.9 C
>   ID-2: /dev/nvme1n1 vendor: Samsung model: SSD 970 EVO Plus 1TB
>     size: 931.51 GiB temp: 43.9 C
>   ID-3: /dev/sda vendor: Seagate model: ST2000DM006-2DM164 size: 1.82 TiB
>   ID-4: /dev/sdb vendor: Seagate model: ST8000DM004-2U9188 size: 7.28 TiB

> Partition:
>   ID-1: / size: 447.75 GiB used: 68.46 GiB (15.3%) fs: ext4
>     dev: /dev/nvme0n1p2
>   ID-2: /boot/efi size: 998 MiB used: 288 KiB (0.0%) fs: vfat
>     dev: /dev/nvme0n1p1

> Swap:
>   ID-1: swap-1 type: partition size: 8.8 GiB used: 24.8 MiB (0.3%)
>     dev: /dev/nvme0n1p3

> Sensors:
>   System Temperatures: cpu: 79.5 C mobo: 41.0 C gpu: amdgpu temp: 52.0 C
>   Fan Speeds (RPM): N/A gpu: amdgpu fan: 0

> Info:
>   Processes: 358 Uptime: 2h 18m Memory: 31.24 GiB used: 9.25 GiB (29.6%)
>   Init: systemd Compilers: gcc: 12.2.1 clang: 15.0.7 Packages: 1065 Shell: Zsh
>   v: 5.9 inxi: 3.3.26

**Comment by euokyun** [comment]
In my case proton 8 has the problem. proton 7-53 works fine.

**Comment by Mar0xy** [comment]
Like said above all proton 8 versions have issues with the game it's recommended to downgrade wine version in launcher
