### ISSUE TITLE
Fails to download Wine (guessing DXVK too) with PathNotMounted on flatpak in Steam Deck

### ISSUE THREAD

**Issue by OscarCamposLKWD** [an-anime-team/the-honkers-railway-launcher#20]
Hi there, first let me thank you for this awesome project, it is great to don't have to take care of installing and configuring every thing manually oneself. Keep the good work!

I have an issue using the flatpak version in Steam Deck. The launcher just gives me an error about the target path of the wine download not being mounted, I did check the directory I choose for the download and the `components` directory is there with all the contents of the git repository with the json files etc, what means that the binary has access to the drive and can write to it, it is just the download what fails with the error below

Context:

```
2023-05-23T12:40:45.462889Z TRACE anime_game_core::installer::installer: Checking free space availability
    at /run/build/railway/cargo/vendor/anime-game-core/src/installer/installer.rs:84
    in anime_game_core::installer::installer::install with self: Installer { downloader: Downloader { uri: "https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-5/wine-lutris-GE-Proton8-5-x86_64.tar.xz", length: Some(93638032), chunk_size: 131072, continue_downloading: true }, temp_folder: "/var/run/media/mmcblk0p1/honkairs" }, unpack_to: "/var/run/media/mmcblk0p1/honkairs/runners"
```

Actual error:

```
2023-05-23T12:40:45.465019Z ERROR honkers_railway_launcher::ui::first_run::download_components: Failed to download wine: Path is not mounted: "/var/run/media/mmcblk0p1/honkairs/wine-lutris-GE-Proton8-5-x86_64.tar.xz"
    at src/ui/first_run/download_components.rs:389
    in anime_game_core::installer::installer::install with self: Installer { downloader: Downloader { uri: "https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-5/wine-lutris-GE-Proton8-5-x86_64.tar.xz", length: Some(93638032), chunk_size: 131072, continue_downloading: true }, temp_folder: "/var/run/media/mmcblk0p1/honkairs" }, unpack_to: "/var/run/media/mmcblk0p1/honkairs/runners"

  2023-05-23T12:40:45.465229Z ERROR honkers_railway_launcher::ui::components::progress_bar: Downloading error: PathNotMounted("/var/run/media/mmcblk0p1/honkairs/wine-lutris-GE-Proton8-5-x86_64.tar.xz")
    at src/ui/components/progress_bar.rs:168
    in relm4::component::r#async::builder::update_with_view with input: UpdateFromState(InstallerUpdate(DownloadingError(PathNotMounted("/var/run/media/mmcblk0p1/honkairs/wine-lutris-GE-Proton8-5-x86_64.tar.xz")))), component: "honkers_railway_launcher::ui::components::progress_bar::ProgressBar", id: "0x7fff55956db0"
```

I actually have experience with Rust but I have no clue how to make a flatpak, anyway, let me know how can I give you a hand to solve this issue.

P.S: the installation works perfectly fine in all my other Linux rigs

**Comment by Mar0xy** [comment]
This tends to happen for the occasional odd few while yes the flatpak indeed give permissions to media devices sometimes flatpak screws something up in the background with the permissions making it work for certain things and not for others.

I recommend trying to give it proper permissions again via flatseal even if the git repos are there if that doesn't work try using 7-43 instead of 8-5

**Comment by OscarCamposLKWD** [comment]
Sorry for the delay, it took me a while to test everything I wanted to test. This is what I did

1. Re-install the flatpak with `--user` 
2. Nuke my whole flatpak installation
3. Add the repo to the system
4. Try installing on system  (same error)
5. Nuke everything
6. Add repo to user
7. Try install on user (same error)

Doesn't looks like I can make it work in any way, not sure if is an issue on my side but I completely nuked my whole flatpak installation removing the flathub and moe.launcher repos and reinstalling
