### ISSUE TITLE
What patch version is the launcher supposed to be using right now?

### ISSUE THREAD

**Issue by MYSTICALMUSICAL** [an-anime-team/the-honkers-railway-launcher#203]
The patch version currently downloaded is 4.1.0.
The text is in red, and hovering over it with the cursor displays, "We have some concerns about this patch version."
Is it safe to play with this version, or is it outdated?

**Comment by Caliel666** [comment]
that is the latest version and the message is correct, i'm not going to explain the entire context here but they changed some stuff in the game that could mean that they want to send those funny scripts again and mass ban people, therefor there is concern, but so far so good, it's as dangerous to play now as it was before
