### ISSUE TITLE
120 FPS support with regedit

### ISSUE THREAD

**Issue by Friedforks** [an-anime-team/the-honkers-railway-launcher#206]
## What's the problem
I'm currently running star rail with soda using the launcher. It worked find but it's only limited to 60 FPS. 

In windows, editing the registry HKEY_CURRENT_USER\Software\miHoYo GraphicsSettings_Model_h2986158309 and changing it to fps: 120 will make the game running at 120 FPS. I tried to do this also in Linux but it failed. 

## What have I done
I found out that the "GraphicsSettings_Model_h2986158309" only exist in user.reg under the folder $launcherhome/prefix/ 

After editing the hexadecimal registry with an ASCII converter, I saved it and relaunched the game. 

But the game launched in 60 FPS, and it seems like user.reg is being automatically updated, and changed to the previous registry with 60FPS:
![image](https://github.com/user-attachments/assets/be74055c-2e2f-4ae0-925d-6c60da79defb)

There's no "GraphicsSettings_Model_h2986158309" under $launcherhome/prefix/pfx/user.reg nor found by using the gui $launcherhome/runners/soda-9.0-1-x86_64/bin/regedit 

I simply want to play my game in 120 FPS. How do I make this work?

**Comment by Friedforks** [comment]
Solved. Thanks!

**Comment by Kataiser9** [comment]
Almost certainly a stupid question, but has something changed to make this not work? Just tried this.

I can manually edit user.reg as expected, but every time I actually launch the game, it reverts the file to what it was before I changed it. I also tried using the regedit GUI for the prefix - same deal. Nobara 42 if it matters.
