### ISSUE TITLE
Game possibly fixed to prevent linux users from using the patch 

### ISSUE THREAD

**Issue by Riktam-Santra** [an-anime-team/the-honkers-railway-launcher#22]
It seems that they are able to detect the patch and ban users. 

I have been ban after midnight ![Screenshot_2023-05-25-09-37-30-71_f940ae8776cd4aedda1adc27c5d1f2d6.jpg](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/32616925/552e2aef-d86e-4e0c-8a2e-75e3dcf03b63)

Ik the screenshot is from Android (because I'm outside) but I swear this has happened because of the linux patch.

NOTE: I'm not telling you people are liable for this in any way. I'm just bringing it to your notice and to warn others.

**Comment by Mar0xy** [comment]
We already know of this from our Discord and have already given a warning out about it.

Please wait until @mkrsym1 has more to say about it/updates.

**Comment by klpod221** [comment]
I got banned too, hope you guys can fix it soon.

**Comment by UnKownOwO** [comment]
I got banned too 
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/94818215/8dc7d457-6f13-4ca5-8b04-8b7fb1f71f7b)

**Comment by Pouncingkitten** [comment]
> We already know of this from our Discord and have already given a warning out about it.

I think adding a warning or notification to the launcher for this kind of information would be useful. Not all of us use Discord.

**Comment by OscarCamposLKWD** [comment]
I also got banned

**Comment by Mar0xy** [comment]
New version released with new patch we won't provide the details on how to make it functional though out of safety reasons and you will have to check how to do it yourself.
