### ISSUE TITLE
被封号了 Has been ban

### ISSUE THREAD

**Issue by Starsdust2004** [an-anime-team/the-honkers-railway-launcher#23]
已被封禁至6月1日，请使用时注意安全
未使用任何其它功能（如解锁fps）
仅在此提醒各位
已提交申诉，我会在有消息后 Close issue

Has been banned until June 1, please be careful when using it
Not using any other features (such as unlocking fps)
Just a reminder to everyone
Submitted a complaint, I will close issue when I hear something

最新消息，他们拒绝为我解封账户，这是否说明了他们其实并不愿意为了少部分的Linux用户来多花精力，或者是厌恶这些超出他们掌控的玩家？

Newsflash, they refuse to unblock my account, does this show that they don't actually want to go the extra mile for a small number of Linux users, or are they sick of these players who are beyond their control?

![截图 2023-05-25 20-09-58](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/61131579/51213444-9339-439e-9852-0fbf62f3536f)

**Comment by PadTrick** [comment]
same here.
DONT USE THIS LAUNCHER ANYMORE !!!

**Comment by elfennani** [comment]
![Screenshot_20230525-185016_Honkai_ Star Rail.png](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/30730500/3e1e24bf-678f-4989-8dff-b7c1382c48b1)

Well me as well

**Comment by BenjaminGalliot** [comment]
Same here!

Does it mean we can’t play on Linux anymore?

**Comment by elfennani** [comment]
> Same here!
> 
> Does it mean we can’t play on Linux anymore?

Yeah probably, this is likely was targeted since nobody other than Linux players got banned on the same day. A user on discord got banned even through the last time he played was three days ago

**Comment by QRQaccount** [comment]
Same here

I am concerned if this means they will ban other launchers like [an-anime-game-launcher](https://github.com/an-anime-team/an-anime-game-launcher)

**Comment by Mar0xy** [comment]
Just for info:
1. No, the other launchers aren't affected and won't be
2. Not just linux users were banned, cheat users and etc also got banned as this was a general move to ban cheaters but it crossfired(which got confirmed after intensive research as to how it happened) and also flagged users that had extra files in the directory
3. The patch has been updated with a new branch by now for testing which is suppose to fix all the issues that resulted in the bans

**Comment by CavaleriOmar** [comment]
> ![Screenshot_20230525-185016_Honkai_ Star Rail.png](https://user-images.githubusercontent.com/30730500/240995275-3e1e24bf-678f-4989-8dff-b7c1382c48b1.png)
> 
> Bene anche io
> 
> Modifica: l'ultima volta che ho suonato su Linux è stato ieri pomeriggio, il che significa che ci vogliono quasi 19 ore prima che tu ottenga il divieto.

I've banned until only 4 hours of game
