### ISSUE TITLE
Cannot install patch

### ISSUE THREAD

**Issue by fsl3118** [an-anime-team/the-honkers-railway-launcher#24]
![截图_The Honkers Railway Launcher_20230527105844](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/134755278/8bdea446-40d6-4ce1-be74-5ad1fddeaa33)
What happened? I tried to install the patch by the launcher but failed.
I also tried to install it manually, but failed again!
![截图_deepin-terminal_20230527105907](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/134755278/7f6637d5-cb8b-4e4e-bc1c-54851512299b)
Now I can't install the patch, I have to play the game on Netease Cloud Games now, but I can't afford it for a long time.

**Comment by krypt0nn** [comment]
I see that you're from China so missed everything happened. Let me summarise everything: we were banned. Devs were trying to ban cheaters, but our patch in some things looked similarly to cheats they were using, so devs' AC marked us as cheaters and we were banned. Now it's not safe to play the game. We research ways to prevent such things in future. Other games are still playable and similar situation should not happen
