### ISSUE TITLE
Failed to sync components index (flatpak)

### ISSUE THREAD

**Issue by dibalikpohon** [an-anime-team/the-honkers-railway-launcher#25]
I found problems when running the launcher.

When choosing the default paths, the Launch Folder points to:
`/home/[user]/.var/app/[flatpak_appId]/data/honkers-railway-launcher`

After clicking Continue, the launcher proceed normally to download Wine and DVXK screen, but a toast shows saying "Failed to sync components index" and my terminal outputs this message:
```
  2023-05-27T14:04:41.036243Z  WARN anime_game_core::traits::git_sync: Given local repository folder doesn't exist
    at /run/build/railway/cargo/vendor/anime-game-core/src/traits/git_sync.rs:24

  2023-05-27T14:04:41.044235Z ERROR honkers_railway_launcher::ui::first_run::main: Failed to sync components index
    at src/ui/first_run/main.rs:224

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/ui/first_run/download_components.rs:315:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Clicking "Details" on the toast output a log as shown:
[debug.log](https://github.com/an-anime-team/the-honkers-railway-launcher/files/11584574/debug.log)

Continue clicking Download made the launcher exit. Another log outputted to the terminal was:
```
thread 'main' panicked at 'The runtime of the component was shutdown. Maybe you accidentally dropped a controller?: DownloadWine', /run/build/railway/cargo/vendor/relm4-0.6.0-beta.1/src/channel/component.rs:66:34
```

Pop!_Os 22.04 LTS; 64-bit; GNOME version 42.5; Windowing System X11;

**Comment by dibalikpohon** [comment]
Hi. Just to let you know that I do not run the app by cloning this repo. I use the flatpak version,

The app now wants to download the components (Wine & DXVK) right now, by cloning components repo to the installation folder. Thank you for the solution.

**Comment by Who-ShioRin** [comment]
> Hi. Just to let you know that I do not run the app by cloning this repo. I use the flatpak version,
> 
> The app now wants to download the components (Wine & DXVK) right now, by cloning components repo to the installation folder. Thank you for the solution.

bro, I have the same problem with flatpak version. Can you tell me the 'path' of installation folder you told?
