### ISSUE TITLE
Don't Play, the new patch did not help at all.

### ISSUE THREAD

**Issue by Clyde-Timonera** [an-anime-team/the-honkers-railway-launcher#27]
You'll certainly get suspended for "3rd party software" or "Security Reasons" like Wine would support it in the first place, *Cough* Bungie.
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/78290310/6bec52b7-c34c-480b-a4b7-5c66bc096f7c)

**Comment by snoweuph** [comment]
bro the launcher litteraly warns you curently when trying to play, that the game currently isnt save to play

**Comment by Xathros1** [comment]
just to make sure, you were using the new mitigations patch?

**Comment by jfichen** [comment]
SAME PROBLEM, WE EVEN HAVE THE SAME SUSPEND-UNTIL TIME

**Comment by cybik** [comment]
@jfichen don't yell.

Though, thank you for reporting about CN bans.

**Comment by jfichen** [comment]
> 

😂 the CAP was unintentional, but overlooked…

**Comment by Clyde-Timonera** [comment]
> just to make sure, you were using the new mitigations patch (which you'd have to apply manually)? Not the old one?

Yeah, I've modified the launcher to use the mitigations patch.

**Comment by Mar0xy** [comment]
New version released with new patch we won't provide the details on how to make it functional though out of safety reasons and you will have to check how to do it yourself.
