### ISSUE TITLE
Failed to patch game

### ISSUE THREAD

**Issue by nekkomimi** [an-anime-team/the-honkers-railway-launcher#28]
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/93983493/01246cb8-6af2-4a60-bffb-77a1a65d57a1)

anyone know how to solve ?

**Comment by Mar0xy** [comment]
Read what it says before asking stuff.

**Comment by Cha14ka** [comment]
It literally says "patch is unsafe". The developers blocked the installation of the patch because there was a wave of bans for using it.
