### ISSUE TITLE
Was this launcher abandoned?

### ISSUE THREAD

**Issue by fsl3118** [an-anime-team/the-honkers-railway-launcher#30]
The game has been updated to version 1.1.0 for a few days. But there is no new patch here, even no information about new game version! It seems that the launcher was abandoned, and we cannot play this game on linux anymore.
So, was it really abandoned? Will there be any new patch appear?

**Comment by mkrsym1** [comment]
Patch development was not abandoned. Read the issues on the patch repository

**Comment by krypt0nn** [comment]
No it was not abandoned

**Comment by krypt0nn** [comment]
UPD: thanks to bros from discord server I noticed that you're from China. Perhaps you could join our matrix server? It's bridged to the discord so you could contact with us directly
