### ISSUE TITLE
Move to jadeite patch

### ISSUE THREAD

**Issue by Clyde-Timonera** [an-anime-team/the-honkers-railway-launcher#31]
Astra has been turned into a LEGACY patch meaning it will never be touched again, and astra's been causing a lot of bans lately and jadeite is a new patch by the same person for 1.1, The launcher will need to migrate to jadeite since astra's now dead

**Comment by krypt0nn** [comment]
-_-

**Comment by Mar0xy** [comment]
> new patch by the same person

We know that as the patch creator is literally in our discord and constantly asking for testers as the Jadeite patch **SHOULD NOT** be used currently unless you 100% understand the risk that triggering a ban is still high
