### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by Phongvngg1** [an-anime-team/the-honkers-railway-launcher#38]
thread 'main' panicked at 'Failed to create launcher folder: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/main.rs:72:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by krypt0nn** [comment]
Stop using symlinks. Solved

**Comment by Phongvngg1** [comment]
i found a file which named "honkers-railway-launcher" so i deleted, done
