### ISSUE TITLE
BUG: When I changed my network connection, the game failed to start.

### ISSUE THREAD

**Issue by fsl3118** [an-anime-team/the-honkers-railway-launcher#45]
Jadeite is normal when I'm using my broadband at home.
But when I go outside, I have to using WLAN. Then the patch returns an error:
![截图_The Honkers Railway Launcher_20230619155457](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/134755278/edab9432-e2fa-43e3-a8f5-6508f6d96e80)
![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/134755278/350b4428-d3d2-4393-ad24-3e05ffe9e9ba)
[debug.log](https://github.com/an-anime-team/the-honkers-railway-launcher/files/11785695/debug.log)

**Comment by krypt0nn** [comment]
Looks like patch repo is unavailable now

![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/29639507/1859b9ed-a844-4f02-be51-b73427c00e40)

**Comment by fsl3118** [comment]
Seems to be fixed now
