### ISSUE TITLE
the launcher crashes with a log 

### ISSUE THREAD

**Issue by HATERVACER** [an-anime-team/the-honkers-railway-launcher#5]
whenever I try launching it, it looks something like this:

```
$ ./honkers-railway-launcher
./honkers-railway-launcher: symbol lookup error: ./honkers-railway-launcher: undefined symbol: gtk_picture_set_content_fit
```

I'm using ubuntu 22.04 an the anime-game-launcher works just fine

**Comment by nolliv22** [comment]
What is the version of your libadwaita?
I've got a similar error because the version of libadwaita I installed with apt was 1.1.
I built the latest version from source (1.4) and it worked.

**Comment by Mar0xy** [comment]
exactly as said above we do not recommend using any of our launchers via binary on distros which stay behind massively on releases of packages.

Please switch to flatpak instead.
