### ISSUE TITLE
Unable to Disable Telemetry, or progress past that point

### ISSUE THREAD

**Issue by PONEKO** [an-anime-team/the-honkers-railway-launcher#51]
I am running on Arch, however after being asked for my sudo password to authorize the disabling, nothing happens and nothing progresses.

https://github.com/an-anime-team/the-honkers-railway-launcher/assets/126267978/210adb1d-77cd-45ad-969a-8127d8206552

(To show where I am stuck at, i attached an image)

I downloaded the 1.2.2 version of the launcher using the AUR

Anime Launcher SDK: 1.8.2
Anime Game Core: 1.13.1

GTK: 4.10.4
libadwaita: 1.3.3
pango: 1.50.14
cairo: 1.17.8

EDIT:
After running it through the terminal, I have found this error message:
0.0.0.0 log-upload-os.hoyoverse.com
0.0.0.0 sg-public-data-api.hoyoverse.com
 >> /etc/hosts
  2023-07-13T14:07:44.330700Z  WARN anime_game_core::games::star_rail::telemetry: Server is not disabled: log-upload-os.hoyoverse.com
    at /var/home/observer/.cargo/git/checkouts/anime-game-core-31370ac61699cd7f/e8b9956/src/games/star_rail/telemetry.rs:21

To the best of my ability, I could not find the path var/home, nevermind all that should be following it

**Comment by krypt0nn** [comment]
Known bug, will be fixed in #52
