### ISSUE TITLE
openSUSE Tumbleweed instructions are wrong

### ISSUE THREAD

**Issue by tn5421** [an-anime-team/the-honkers-railway-launcher#64]
To summarize the issue, the installation instructions for openSUSE Tumbleweed include the .repo file when it is not expected or wanted. I would correct this myself, but I can't seem to edit the wiki.

Incorrect: 
`sudo zypper ar -f https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo aatrepo`

Output: 
```
sudo zypper ref
Retrieving repository 'aatrepo' metadata .............................................................................................................................................[error]
Repository 'aatrepo' is invalid.
[aatrepo|https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Valid metadata not found at specified URL
History:
 - [aatrepo|https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'aatrepo' because of the above error.
```

The correct input should be: 
`sudo zypper ar -f https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/ aatrepo`

Affected pages: 
https://github.com/an-anime-team/the-honkers-railway-launcher/wiki/Installation#-opensuse-tumbleweed-rpm
https://github.com/an-anime-team/an-anime-game-launcher/wiki/Installation#-opensuse-tumbleweed-rpm
possibly more

**Comment by Mar0xy** [comment]
> openSUSE Tumbleweed include the .repo file when it is not expected 

This is indeed incorrect please check the documentation: https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg#sec.obsbg.uc.install-from-obs

in step 3 it links directly to the .repo file
