### ISSUE TITLE
can't download the classic background when the launcher is set to Portuguese

### ISSUE THREAD

**Issue by nekoraw** [an-anime-team/the-honkers-railway-launcher#69]
the video shows the problem

https://github.com/an-anime-team/the-honkers-railway-launcher/assets/50468652/c2df4a5d-9d3a-42a4-9726-4e49500decc3

running the aur arch linux version (also reproducible on the flatpak version)
locale is set to pt_BR.UTF-8

**Comment by Mar0xy** [comment]
This is cause there is no classic background for that specific language. You can only use classic view with any of the languages listed on the game's website as those are officially supported languages.

**Comment by nekoraw** [comment]
there is a classic background for portuguese, and it is officially supported because i can select the language in-game

![image](https://github.com/an-anime-team/the-honkers-railway-launcher/assets/50468652/c944bc7f-d3f0-4002-a549-ab647b9ee2e6)

**Comment by nekoraw** [comment]
for some reason they use the pt-pt locale instead of pt-br for the backgound endpoint (the game text is definitively in brazilian portuguese)

changing the language to pt-pt in the config files fixes the issue and can be used as a workaround
