### ISSUE TITLE
how do i uninstall ?

### ISSUE THREAD

**Issue by Pancake20** [an-anime-team/the-honkers-railway-launcher#78]
i found out this version is lot harder to run in my pc than the original windows one, how do i uninstall this thing ?

**Comment by Teapot4195** [comment]
You can't run the original windows one on Linux.
However if you do want to uninstall, `flatpak uninstall --delete-data launcher.moe moe.launcher.the-honkers-railway-launcher` will do.

**Comment by Pancake20** [comment]
> You can't run the original windows one on Linux. However if you do want to uninstall, `flatpak uninstall --delete-data launcher.moe moe.launcher.the-honkers-railway-launcher` will do.

thank you for your help 👍
