### ISSUE TITLE
Luncher does not work anymore.

### ISSUE THREAD

**Issue by Gakomi** [an-anime-team/the-honkers-railway-launcher#83]
It gives the following error:
-Faild to find game diff
-Failed to fetch patch info
-Failed to update launcher state

About 11 hours ago it was working just fine. 
Tested it both on my pc and Steam Deck and the same issue is happening on both.

**Comment by Gakomi** [comment]
Issue seems to be due to an webkit2gtk update. I have reverted back to webkit2gtk-4.0 and now it's working.

**Comment by Ieatillo** [comment]
I have the same issue. How could I revert back?
