### ISSUE TITLE
The honkers launcher reporting an error

### ISSUE THREAD

**Issue by ENDragnee** [an-anime-team/the-honkers-railway-launcher#88]
1 "name" = "honkers-railway-launcher"
  2 "operating_system" = "Linux Rolling Release [64-bit]"
  3 "crate_version" = "1.5.0"
  4 "explanation" = """
  5 Panic occurred in file '/var/home/observer/.cargo/git/checkouts/anime-game-core-31370ac61699cd7f/79fa0ea/src/games/star_rail/voice_data/package.rs' at line 265
  6 """
  7 "cause" = "internal error: entered unreachable code"
  8 "method" = "Panic"
  9 "backtrace" = """
 10
 11    0: 0x55dcb2ce9040 - <unresolved>
 12    1: 0x55dcb2e3e23b - <unresolved>
 13    2: 0x55dcb2db8c64 - <unresolved>
 14    3: 0x55dcb2d81442 - <unresolved>
 15    4: 0x7fd08efd4f69 - <unresolved>
 16    5: 0x7fd08f033327 - <unresolved>
 17    6: 0x7fd08efd3162 - g_main_context_iteration
 18    7: 0x7fd08fd48b16 - g_application_run
 19    8: 0x55dcb2e29297 - <unresolved>
 20    9: 0x55dcb2e293a0 - <unresolved>
 21   10: 0x55dcb2ec4e2d - <unresolved>
 22   11: 0x55dcb2ebd238 - <unresolved>
 23   12: 0x55dcb2ec1dea - <unresolved>
 24   13: 0x7fd08ec71cd0 - <unresolved>
 25   14: 0x7fd08ec71d8a - __libc_start_main
 26   15: 0x55dcb2cc9ef5 - <unresolved>
 27   16:        0x0 - <unresolved>"

**Comment by krypt0nn** [comment]
https://github.com/an-anime-team/the-honkers-railway-launcher/pull/87

**Comment by ENDragnee** [comment]
Thank very much man, your a great guy
