### ISSUE TITLE
Failed to launch game: Telemetry server is not disabled: log-upload-os.hoyoverse.com

### ISSUE THREAD

**Issue by asas1asas200** [an-anime-team/the-honkers-railway-launcher#9]
When I click `launch` button, this error appeared in log as follows:
```
ERROR honkers_railway_launcher::ui::main::launch: Failed to launch game: Telemetry server is not disabled: log-upload-os.hoyoverse.com
    at src/ui/main/launch.rs:11
```

And I resolved by add these lines in `/etc/hosts`:
```
# *** logging servers (oversea)
0.0.0.0 log-upload-os.***.com
0.0.0.0 sg-public-data-api.***.com
```

Consider adding this in FAQ to help people who also have this problem.

**Comment by Mar0xy** [comment]
We do not have this in the FAQ due to the fact that it shows the company and game name for search engines to pick up in those cases we recommend joining the discord or matrix server.
