### ISSUE TITLE
Unhandled exception: page fault on read access to 0x000000000024d7be in 64-bit code

### ISSUE THREAD

**Issue by jejomar** [an-anime-team/the-honkers-railway-launcher#98]
I followed the install instructions for NixOS. Was able to successfully install the launcher, download the game files, but the game won't launch and spits out this error.
[backtrace.txt](https://github.com/an-anime-team/the-honkers-railway-launcher/files/13775771/backtrace.txt)

**Comment by mkrsym1** [comment]
Try the regular troubleshooting steps: change Wine versions, delete your prefix. If that fails, try reinstalling the game.

It would be nice if you provide the full terminal output too, not only the backtrace.

**Comment by jejomar** [comment]
> Try the regular troubleshooting steps: change Wine versions, delete your prefix. If that fails, try reinstalling the game.
> 
> It would be nice if you provide the full terminal output too, not only the backtrace.

I did try both earlier still nada. Was able to run the game by reinstalling Wine. Thanks!
